### ISSUE TITLE
Can't find `The return of the quantum cat` when I searched for it.

### ISSUE THREAD

**Issue by cckole** [btimofeev/instead-launcher-android#3]
I wanted to download all the available English games but `THE RETURN OF THE QUANTUM CAT`  wasn't among the listed games in English. I was only able to download `Mainland`, `Return of the red Hood`, and `Crash drive`. Was that an omission or what?

![Screenshot_20190518-170526](https://user-images.githubusercontent.com/36272218/57972293-356b8080-7990-11e9-80f9-a53b3889741d.png)

**Comment by Minoru** [comment]
Worked for me with v0.7 just now. Try updating the repository and searching again. (To update the repository, press the three dots next to the search bar, and tap "Update repository".)

**Comment by cckole** [comment]
Nice. I found it. Thanks for the swift reply.

**Comment by Minoru** [comment]
@btimofeev If search returned no results, it might make sense to display a grayed-out message in that blank white area, saying something like "Nothing found. Update the repositories and try again".

**Comment by cckole** [comment]
I think that would be a nice idea. It will be a kind of direction for users. Good point.

**Comment by btimofeev** [comment]
@cckole There are two more games in English: "I.A.G. Alpha" and "Constellation".

**Comment by btimofeev** [comment]
message added in https://github.com/btimofeev/instead-launcher-android/commit/5a915c6f4c78bd6558a330e0b362b77b0d577e67
