### ISSUE TITLE
Crash on first start if repository data is replaced

### ISSUE THREAD

**Issue by Self-Perfection** [btimofeev/instead-launcher-android#6]
Tried running the app for the first time while connected to Wi-Fi hotspot redirecting all requests to captive portal.

Attempts to press :heavy_plus_sign: on welcome screen caused crashes without any error message visible to me. I suppose that is because the app got something unexpected instead of http://instead-games.ru/xml.php and could not parse it.

Though the onus is partially on instead-games.ru that is not available via https.

**Comment by btimofeev** [comment]
Thank you. I tried to fix this crash in commit ea00604
