### ISSUE TITLE
add changelog

### ISSUE THREAD

**Issue by leela52452** [btimofeev/instead-launcher-android#7]
can you please add changelog.
what is [CHANGELOG](https://en.m.wikipedia.org/wiki/Changelog) ?

**Comment by btimofeev** [comment]
I do not have a separate changelog file, but you can see it in these files https://github.com/btimofeev/instead-launcher-android/tree/master/fastlane/metadata/android/en-US/changelogs

But you're right, I will add a changelog as a separate file.

**Comment by Minoru** [comment]
JFYI, [Keep a changelog](https://keepachangelog.com/en/1.0.0/) provides a nice template that many repositories use. The benefit of a template is that it's the same across a lot of projects, to people have easier time scanning it for stuff they're interested in.

**Comment by btimofeev** [comment]
Thanks, added in the commit d0148653e55980193e78a20e4f3f59eb8208d608
