### ISSUE TITLE
F-Droid fails to build

### ISSUE THREAD

**Issue by licaon-kter** [btimofeev/instead-launcher-android#8]
Ref https://f-droid.org/wiki/page/org.emunix.insteadlauncher/lastbuild_800

**Comment by btimofeev** [comment]
I know about it. On my computer it compiles with NDK r20. I already created [Merge Request](https://gitlab.com/fdroid/fdroiddata/merge_requests/5736), but have not yet accepted it.

**Comment by licaon-kter** [comment]
Thanks
